### ISSUE TITLE
Do we want to pass around the current config object?

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#1]
We are passing around the config object in such a way that it is required. Do we want to assume this everywhere?

@Jim-Holmstroem @FelixAbrahamsson What do you think?

**Comment by Jim-Holmstroem** [comment]
are you refering to the `config` that is the argument to some of the functions?

**Comment by Jim-Holmstroem** [comment]
you don't want to pass along things like "where to log" "where is the database" etc all over the place

**Comment by Jim-Holmstroem** [comment]
usually I'm pro having decent defaults that assumes as little as possible, then having the option to override it

```
import workflow.config import default_config

def foo(a, config={}):
    config = dict(default_config, **config)
    ...    
```

**Comment by samedii** [comment]
@Jim-Holmstroem  It would be good to consider to have a default config that we reuse. It is not what I am referring to here though but I didn't explain it well.

At the moment we are using argparse in the begining of every guild operation which creates a config object (dictionary). This object often has a similar structure for the "train operation" between projects.

In the current code we are assuming things about this config dictionary (i.e. that certain keys will be there).
Edit: We are also passing this config object around pretty much everywhere.

I wanted to bring this up as a design question - Do we want our workflow library to work like this and what could the options be?
