### ISSUE TITLE
Some of the handlers are assuming datasets with a known length

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#13]
Do we want to assume this? We could probably make changes to handle this in coop-article-detection if we want

**Comment by FelixAbrahamsson** [comment]
From what I can find it's only `ml_workflow.ignite.handlers.attach_validation_progress_bar` that assumes a known length of the validation dataset, which it needs to compute the number of validation steps. I think it could instead just take the number of steps as an argument.
