### ISSUE TITLE
How should we handle test and development?

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#3]
I started off using the same method as in ml projects with guild (requirements.txt + guild.yml) but this may not be what we want to do. What do you think? @FelixAbrahamsson  @Jim-Holmstroem 

_I think it's normal to define dependencies in a requirements.txt file for development and normal requirements in the setup.py but I might be wrong._

_I used guild.yml only to specify the python version for testing._

**Comment by Jim-Holmstroem** [comment]
I think the most common thing is to read the requirements.txt in setup.py, this to not duplicate code

Still not super familiar with guild but a few compiled languages actually split dev-dependencies and dependencies
typescript for example has devDependencies (things you need to be able to build and test) and dependencies (dependencies needed when running it)

so if we have things that are dev dependencies (like matplotlib etc) I think we should have requirements-dev.txt (or do something with guild.yml) and a requirements.txt

**Comment by samedii** [comment]
Note that "pip install" does not look at a requirements.txt, only at install_requires in setup.py.

The requirements.txt are the dev-dependencies at the moment

**Comment by samedii** [comment]
Closing. Let's try and work with this setup and see how it feels
