### ISSUE TITLE
Logging not working in VSCode

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#30]
Stops working when presenting validation progress bar.

If validation progress bar is disabled then training works but the logger prints text in a weird way

Works well in terminal output

**Comment by FelixAbrahamsson** [comment]
Is it because it's being printed to sys.stderr perhaps? I had to print to stderr for it to work with guild

**Comment by samedii** [comment]
Yes I started reading about it and that could be the issue. I'll check if it helps
