### ISSUE TITLE
Check if guild still needs stderr

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#39]
Otherwise switch to stdout

**Comment by FelixAbrahamsson** [comment]
Closing this because of decisions made in #52

**Comment by samedii** [comment]
Discussed with Felix. This is more related to if we can output progress bars to stdout with guild in newer versions

**Comment by FelixAbrahamsson** [comment]
A quick test with stdout instead of stderr seems to produce the same terminal output. Looks like it works with the most recent version of guild.
