### ISSUE TITLE
Log model score to tensorboard

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#50]
Should be easy to do. Reuse tensorboard logger

**Comment by FelixAbrahamsson** [comment]
Do you mean [this](https://github.com/codewell/ml-workflow/blob/1feb233772fce81a583cb628de33aec5300bfff2/workflow/ignite/handlers/early_stopping.py#L30)?

**Comment by samedii** [comment]
Yes but we should log the metric to tensorboard so we can look at it in guild (preferably with the existing tensorboard_logger) and also not inside that handler imo.
