### ISSUE TITLE
Fix learning rate logging

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#51]
The logging is probably incorrect but it might also be the learning rate scheduler that is behaving incorrectly.
![image](https://user-images.githubusercontent.com/1872050/73894101-b569ab80-487b-11ea-9568-2026ae850d39.png)

We are probably logging before the scheduler has changed the learning rate value

**Comment by FelixAbrahamsson** [comment]
Yes, I remember seeing similar behaviour when I was first implementing warmup and cyclical LR with ignite and wanted to see if it was working properly. I think it was because I was logging before the update occured.
