### ISSUE TITLE
Guild no longer catches the logged evaluation metrics

### ISSUE THREAD

**Issue by FelixAbrahamsson** [codewell/ml-workflow#52]
See https://github.com/codewell/ml-workflow/blob/master/workflow/ignite/handlers/metrics_logger.py
I think it's just because of the added whitespace at lines 22, 25, 27. The following change fixes the problem
```python
def _print(self, engine):
    if len(engine.state.metrics) >= 1:
        target_len = max(len(name) for name in engine.state.metrics.keys())
        tqdm_print(f'--- {self.name} evaluation ---')
        for metric, value in engine.state.metrics.items():
            padding = ' ' * (target_len - len(metric))
            if hasattr(value, '__len__'):
                tqdm_print(f'{self.name}_{metric}:')
                tqdm_print(str(value))
            elif is_float(value):
                tqdm_print(f'{self.name}_{metric}:{padding} {value:.4f}')
            else:
                tqdm_print(f'{self.name}_{metric}:{padding} {value}')
```
Curiously, the extra print statement `tqdm_print(f'--- {self.name} evaluation ---')` is needed or otherwise the first metric being logged doesn't get caught by guild. I remember @samedii saying something about guild being able to catch Tensorboard loggings instead, maybe that's a better solution? I like the way output is currently logged, it's easy to read, would be a shame to have to go back to the old way.

**Comment by samedii** [comment]
Guild is catching them but does not show them by default. Had to ask Garret but you can use the -c flag to see them

**Comment by samedii** [comment]
It is only catching them because they are logged to tensorboard. I do not think we should use the terminal to log values.

See https://github.com/guildai/guildai/issues/125

**Comment by gar1t** [comment]
@FelixAbrahamsson The default pattern that Guild uses to capture scalars from output is `^(\key):\s+(\value)$` - so those extra spaces should be fine. That's a bit of a nice coincidence though. If your pattern changes, you can configure what Guild uses via the `output-scalars` operation attr.

I've got some examples here:

https://www-pre.guild.ai/cheatsheets/guildfile/#output-scalars

(Note this ^ is a staged pre-release site - still under development.)

I do agree with @samedii in this case - if you're already using TensorBoard summaries in your code, that's better IMO than using Guild to scrape output. The output scalars feature in Guild is there for folks who don't want to bother with logging via TB summaries.

In this case, I'd disable output scalars altogether so Guild doesn't waste cycles scanning output.

```
op:
  output-scalars: no
```

I'm looking at this issue of scalars containing `/` not showing up in compare now.

**Comment by FelixAbrahamsson** [comment]
After thinking about it I agree that disabling output scalars for the operation and just using the -c flag to compare the desired metrics is the best solution.
