### ISSUE TITLE
Merge cookie-cutter project creator?

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#7]
I think Felix' project creator fits in well in the workflow repository. I suggest we move it here. What do you think? @FelixAbrahamsson @Jim-Holmstroem

**Comment by Jim-Holmstroem** [comment]
I'll vote to merge it unless there is some technical issue with the cookie-cutter

**Comment by FelixAbrahamsson** [comment]
The template needs to be in its own repo for Cookiecutter to work
