### ISSUE TITLE
Should load_best_model be a static method on ModelCheckpoint?

### ISSUE THREAD

**Issue by samedii** [codewell/ml-workflow#79]

**Comment by FelixAbrahamsson** [comment]
I agree that that would be nice. What would you rather do, implement our own ModelCheckpoint or make an issue for the ignite library?

**Comment by samedii** [comment]
We actually already have our own wrapper for ModelCheckpoint so I thought it would be easy to do if we prefer it that way :)

**Comment by FelixAbrahamsson** [comment]
Oh I didn't see that! Yes, that makes sense then. It's very specific to the ignite naming so it probably shouldnt be in `workflow.torch` anyway
